type TopicSeedData = {
  slug: string
  name: string
  order: number
  description: string
  estimatedMinutes: number
  prerequisiteSlugs: string[]
  examWeight: number
  examTypes: ('jamb' | 'waec' | 'neco' | 'undergraduate')[]
}

type SubjectSeedData = {
  slug: string
  name: string
  examTypes: ('jamb' | 'waec' | 'neco' | 'undergraduate')[]
  description: string
  hue: string
  topics: TopicSeedData[]
}

export const subjects: SubjectSeedData[] = [
  {
    slug: 'english',
    name: 'English Language',
    hue: '#3F5B7F',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Core English language skills covering comprehension, grammar, writing, and oral English required for JAMB, WAEC, and NECO.',
    topics: [
      {
        slug: 'comprehension',
        name: 'Comprehension',
        order: 1,
        description: 'Reading and understanding passages, answering inferential and literal questions accurately.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.12,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'summary-writing',
        name: 'Summary Writing',
        order: 2,
        description: 'Identifying main points in a passage and presenting them concisely in your own words.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['comprehension'],
        examWeight: 0.10,
        examTypes: ['waec', 'neco'],
      },
      {
        slug: 'lexis-and-structure',
        name: 'Lexis and Structure',
        order: 3,
        description: 'Vocabulary in context, word classes, and sentence structures tested in objective questions.',
        estimatedMinutes: 75,
        prerequisiteSlugs: [],
        examWeight: 0.15,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'essay-writing',
        name: 'Essay Writing',
        order: 4,
        description: 'Writing formal and informal letters, articles, debates, narratives, and expository essays with clarity and coherence.',
        estimatedMinutes: 90,
        prerequisiteSlugs: ['comprehension'],
        examWeight: 0.15,
        examTypes: ['waec', 'neco'],
      },
      {
        slug: 'speech-work',
        name: 'Speech Work and Oral English',
        order: 5,
        description: 'Phonetics, stress patterns, intonation, vowel and consonant sounds relevant to Nigerian English.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'figures-of-speech',
        name: 'Figures of Speech',
        order: 6,
        description: 'Identification and use of simile, metaphor, personification, hyperbole, irony, and other literary devices.',
        estimatedMinutes: 50,
        prerequisiteSlugs: [],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'register-and-usage',
        name: 'Register and Usage',
        order: 7,
        description: 'Appropriate language use in different contexts — formal, informal, and specialist registers.',
        estimatedMinutes: 45,
        prerequisiteSlugs: ['lexis-and-structure'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'literature-poetry',
        name: 'Literature — Poetry',
        order: 8,
        description: 'Analysis of prescribed and unseen poems: theme, tone, imagery, and poetic devices.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['figures-of-speech'],
        examWeight: 0.08,
        examTypes: ['waec', 'neco'],
      },
      {
        slug: 'literature-prose',
        name: 'Literature — Prose',
        order: 9,
        description: 'Character, plot, setting, and theme analysis of prescribed prose texts.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['comprehension'],
        examWeight: 0.07,
        examTypes: ['waec', 'neco'],
      },
      {
        slug: 'literature-drama',
        name: 'Literature — Drama',
        order: 10,
        description: 'Understanding dramatic conventions, stage directions, conflict, and theme in prescribed plays.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['comprehension'],
        examWeight: 0.07,
        examTypes: ['waec', 'neco'],
      },
    ],
  },
  {
    slug: 'mathematics',
    name: 'Mathematics',
    hue: '#6B4E8F',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Pure and applied mathematics covering number theory, algebra, geometry, trigonometry, statistics, and calculus.',
    topics: [
      {
        slug: 'number-systems',
        name: 'Number Systems',
        order: 1,
        description: 'Integers, fractions, decimals, surds, indices, and number bases including binary and hexadecimal.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'algebraic-expressions',
        name: 'Algebraic Expressions',
        order: 2,
        description: 'Simplification, factorisation, and manipulation of algebraic expressions and polynomials.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['number-systems'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'quadratic-equations',
        name: 'Quadratic Equations',
        order: 3,
        description: 'Solving quadratic equations by factorisation, completing the square, and using the quadratic formula.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['algebraic-expressions'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'indices-and-surds',
        name: 'Indices and Surds',
        order: 4,
        description: 'Laws of indices and manipulation of surd expressions including rationalisation of the denominator.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['number-systems'],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'logarithms',
        name: 'Logarithms',
        order: 5,
        description: 'Laws of logarithms, change of base, and application to computation and equations.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['indices-and-surds'],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'linear-simultaneous-equations',
        name: 'Linear and Simultaneous Equations',
        order: 6,
        description: 'Solving linear equations, systems of simultaneous equations by substitution and elimination.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['algebraic-expressions'],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'variation',
        name: 'Variation',
        order: 7,
        description: 'Direct, inverse, partial, and joint variation — setting up and solving variation problems.',
        estimatedMinutes: 45,
        prerequisiteSlugs: ['linear-simultaneous-equations'],
        examWeight: 0.05,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'sets',
        name: 'Sets',
        order: 8,
        description: 'Set notation, operations (union, intersection, complement), Venn diagrams, and applications.',
        estimatedMinutes: 50,
        prerequisiteSlugs: [],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'sequences-and-series',
        name: 'Sequences and Series',
        order: 9,
        description: 'Arithmetic and geometric progressions, sum of series, and practical applications.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['algebraic-expressions'],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'trigonometry',
        name: 'Trigonometry',
        order: 10,
        description: 'Sine, cosine, tangent ratios; trigonometric identities; solving triangles using sine and cosine rules.',
        estimatedMinutes: 70,
        prerequisiteSlugs: [],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'circle-geometry',
        name: 'Circle Geometry',
        order: 11,
        description: 'Properties of circles, chord theorems, tangent-radius relationships, and angles in circles.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'statistics',
        name: 'Statistics',
        order: 12,
        description: 'Mean, median, mode, range, frequency tables, histograms, cumulative frequency, and ogive.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'probability',
        name: 'Probability',
        order: 13,
        description: 'Basic probability rules, mutually exclusive events, independent events, and tree diagrams.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['sets'],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'calculus-differentiation',
        name: 'Calculus — Differentiation',
        order: 14,
        description: 'Limits, differentiation from first principles, rules of differentiation, and application to rates of change.',
        estimatedMinutes: 75,
        prerequisiteSlugs: ['algebraic-expressions'],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'calculus-integration',
        name: 'Calculus — Integration',
        order: 15,
        description: 'Integration as the reverse of differentiation; definite and indefinite integrals; area under a curve.',
        estimatedMinutes: 70,
        prerequisiteSlugs: ['calculus-differentiation'],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
    ],
  },
  {
    slug: 'physics',
    name: 'Physics',
    hue: '#2F6B6B',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Foundational and applied physics including mechanics, waves, electricity, magnetism, and modern physics.',
    topics: [
      {
        slug: 'measurement-and-units',
        name: 'Measurement and Units',
        order: 1,
        description: 'SI units, scalars and vectors, dimensions, significant figures, and experimental error analysis.',
        estimatedMinutes: 45,
        prerequisiteSlugs: [],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'kinematics',
        name: 'Motion (Kinematics)',
        order: 2,
        description: 'Equations of motion, distance-time and velocity-time graphs, projectile motion, and relative motion.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['measurement-and-units'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'dynamics',
        name: "Dynamics (Newton's Laws)",
        order: 3,
        description: "Newton's three laws of motion, momentum, impulse, friction, and applications to everyday problems.",
        estimatedMinutes: 65,
        prerequisiteSlugs: ['kinematics'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'work-energy-power',
        name: 'Work, Energy, Power',
        order: 4,
        description: 'Definitions and calculations of work, kinetic and potential energy, conservation of energy, and power.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['dynamics'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'waves-and-sound',
        name: 'Waves and Sound',
        order: 5,
        description: 'Wave properties, types of waves, resonance, the Doppler effect, and characteristics of sound waves.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['measurement-and-units'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'light-optics',
        name: 'Light (Optics)',
        order: 6,
        description: 'Reflection, refraction, total internal reflection, lenses, mirrors, and optical instruments.',
        estimatedMinutes: 70,
        prerequisiteSlugs: ['waves-and-sound'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'heat-and-temperature',
        name: 'Heat and Temperature',
        order: 7,
        description: 'Temperature scales, thermal expansion, specific heat capacity, latent heat, and heat transfer modes.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['measurement-and-units'],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'static-electricity',
        name: 'Electricity (Electrostatics)',
        order: 8,
        description: "Coulomb's law, electric field and potential, capacitors, and charge distribution on conductors.",
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'current-electricity',
        name: 'Current Electricity',
        order: 9,
        description: "Ohm's law, resistance, series and parallel circuits, EMF, internal resistance, and electrical energy.",
        estimatedMinutes: 70,
        prerequisiteSlugs: ['static-electricity'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'magnetism',
        name: 'Magnetism and Electromagnetism',
        order: 10,
        description: 'Magnetic fields, electromagnetic induction, transformers, and the motor principle.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['current-electricity'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'modern-physics',
        name: 'Modern Physics',
        order: 11,
        description: 'Atomic structure, radioactivity, nuclear reactions, half-life, and photoelectric effect.',
        estimatedMinutes: 65,
        prerequisiteSlugs: [],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'electronics',
        name: 'Electronics',
        order: 12,
        description: 'Semiconductors, p-n junction diodes, rectification, transistors, and basic logic gates.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['current-electricity'],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
    ],
  },
  {
    slug: 'chemistry',
    name: 'Chemistry',
    hue: '#8E5A2B',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Physical, inorganic, and organic chemistry including atomic theory, bonding, reactions, and quantitative analysis.',
    topics: [
      {
        slug: 'atomic-structure',
        name: 'Atomic Structure',
        order: 1,
        description: 'Sub-atomic particles, electronic configurations, isotopes, and quantum model of the atom.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'chemical-bonding',
        name: 'Chemical Bonding',
        order: 2,
        description: 'Ionic, covalent, metallic, and coordinate bonding; molecular shapes and polarity.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['atomic-structure'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'stoichiometry',
        name: 'Stoichiometry',
        order: 3,
        description: 'Mole concept, molar mass, empirical and molecular formulae, and reacting quantities.',
        estimatedMinutes: 70,
        prerequisiteSlugs: ['atomic-structure'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'states-of-matter',
        name: 'States of Matter',
        order: 4,
        description: 'Kinetic theory, gas laws (Boyle, Charles, Ideal Gas), properties of solids, liquids, and gases.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'acids-bases-salts',
        name: 'Acids, Bases, and Salts',
        order: 5,
        description: 'pH, neutralisation, types of salts, preparation methods, and ionic equations.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['stoichiometry'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'oxidation-reduction',
        name: 'Oxidation-Reduction (Redox)',
        order: 6,
        description: 'Oxidation numbers, balancing redox equations, and oxidising and reducing agents.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['acids-bases-salts'],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'electrochemistry',
        name: 'Electrochemistry',
        order: 7,
        description: 'Electrolysis, electroplating, Faraday\'s laws, and the electrochemical series.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['oxidation-reduction'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'organic-hydrocarbons',
        name: 'Organic Chemistry — Hydrocarbons',
        order: 8,
        description: 'Alkanes, alkenes, alkynes: nomenclature, structure, isomerism, and reactions.',
        estimatedMinutes: 70,
        prerequisiteSlugs: ['chemical-bonding'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'organic-functional-groups',
        name: 'Organic Chemistry — Functional Groups',
        order: 9,
        description: 'Alkanols, alkanals, alkanones, alkanoic acids, esters, amines, and polymers.',
        estimatedMinutes: 70,
        prerequisiteSlugs: ['organic-hydrocarbons'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'rates-of-reaction',
        name: 'Rates of Reaction',
        order: 10,
        description: 'Factors affecting reaction rate, collision theory, activation energy, and catalysis.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['stoichiometry'],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'chemical-equilibrium',
        name: 'Chemical Equilibrium',
        order: 11,
        description: "Le Chatelier's principle, equilibrium constants, and the Haber and Contact processes.",
        estimatedMinutes: 55,
        prerequisiteSlugs: ['rates-of-reaction'],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'thermochemistry',
        name: 'Thermochemistry',
        order: 12,
        description: 'Enthalpy changes, Hess\'s law, bond energies, and calorimetry calculations.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['stoichiometry'],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
    ],
  },
  {
    slug: 'biology',
    name: 'Biology',
    hue: '#4F7A3F',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Life sciences covering cell biology, genetics, ecology, physiology, and the systems of living organisms.',
    topics: [
      {
        slug: 'cell-biology',
        name: 'Cell Biology',
        order: 1,
        description: 'Cell structure, organelles, prokaryotic vs eukaryotic cells, cell division (mitosis and meiosis).',
        estimatedMinutes: 65,
        prerequisiteSlugs: [],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'genetics-and-heredity',
        name: 'Genetics and Heredity',
        order: 2,
        description: "Mendel's laws, monohybrid and dihybrid crosses, sex-linked inheritance, and mutations.",
        estimatedMinutes: 70,
        prerequisiteSlugs: ['cell-biology'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'evolution',
        name: 'Evolution',
        order: 3,
        description: 'Theories of evolution, natural selection, adaptation, speciation, and evidence for evolution.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['genetics-and-heredity'],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'ecology',
        name: 'Ecology and Environment',
        order: 4,
        description: 'Ecosystems, food chains and webs, energy flow, nutrient cycles, and environmental conservation.',
        estimatedMinutes: 65,
        prerequisiteSlugs: [],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'nutrition',
        name: 'Nutrition',
        order: 5,
        description: 'Autotrophic and heterotrophic nutrition, photosynthesis, and the digestive system in animals.',
        estimatedMinutes: 65,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'respiration',
        name: 'Respiration',
        order: 6,
        description: 'Aerobic and anaerobic respiration, ATP production, and the respiratory system in humans.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['cell-biology'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'excretion',
        name: 'Excretion',
        order: 7,
        description: 'Excretory products, the urinary system, kidney structure and function, and osmoregulation.',
        estimatedMinutes: 55,
        prerequisiteSlugs: [],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'reproduction-plants',
        name: 'Reproduction in Plants',
        order: 8,
        description: 'Asexual and sexual reproduction in plants, flower structure, pollination, fertilisation, and seed dispersal.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'reproduction-animals',
        name: 'Reproduction in Animals',
        order: 9,
        description: 'Male and female reproductive systems, fertilisation, development of the embryo, and parturition.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'nervous-system',
        name: 'Nervous System',
        order: 10,
        description: 'Structure and function of neurons, reflex arc, the brain, spinal cord, and sense organs.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['cell-biology'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'circulatory-system',
        name: 'Circulatory System',
        order: 11,
        description: 'Heart structure, blood composition, blood groups, pulmonary and systemic circulation.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'support-and-movement',
        name: 'Support and Movement',
        order: 12,
        description: 'Skeletal system, types of joints, muscles, and locomotion in vertebrates and invertebrates.',
        estimatedMinutes: 55,
        prerequisiteSlugs: [],
        examWeight: 0.06,
        examTypes: ['jamb', 'waec', 'neco'],
      },
    ],
  },
  {
    slug: 'economics',
    name: 'Economics',
    hue: '#8E7F2B',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Micro and macroeconomic principles covering markets, national income, money, trade, and public finance.',
    topics: [
      {
        slug: 'basic-concepts',
        name: 'Basic Economic Concepts',
        order: 1,
        description: 'Scarcity, choice, opportunity cost, the production possibility frontier, and economic systems.',
        estimatedMinutes: 50,
        prerequisiteSlugs: [],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'demand-and-supply',
        name: 'Demand and Supply',
        order: 2,
        description: 'Laws of demand and supply, elasticity, market equilibrium, shifts in curves, and price mechanism.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['basic-concepts'],
        examWeight: 0.12,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'market-structures',
        name: 'Market Structures',
        order: 3,
        description: 'Perfect competition, monopoly, oligopoly, and monopolistic competition — features and implications.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['demand-and-supply'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'national-income',
        name: 'National Income',
        order: 4,
        description: 'GDP, GNP, NNP measurement methods; economic growth, inflation, and unemployment.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['basic-concepts'],
        examWeight: 0.11,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'money-and-banking',
        name: 'Money and Banking',
        order: 5,
        description: 'Functions of money, commercial and central banking, monetary policy, and credit creation.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['national-income'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'international-trade',
        name: 'International Trade',
        order: 6,
        description: 'Theory of comparative advantage, balance of payments, exchange rates, and trade barriers.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['demand-and-supply'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'public-finance',
        name: 'Public Finance',
        order: 7,
        description: 'Government revenue and expenditure, types of taxes, budget, and fiscal policy.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['national-income'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'population',
        name: 'Population',
        order: 8,
        description: 'Population growth, demographic trends, dependency ratio, and implications for development.',
        estimatedMinutes: 45,
        prerequisiteSlugs: [],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'production',
        name: 'Production',
        order: 9,
        description: 'Factors of production, types of production, division of labour, and scale of production.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['basic-concepts'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'price-determination',
        name: 'Price Determination',
        order: 10,
        description: 'Price fixing, price controls, minimum and maximum prices, and their effects on markets.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['demand-and-supply', 'market-structures'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'agriculture-economics',
        name: 'Agriculture and Nigerian Economy',
        order: 11,
        description: 'Role of agriculture in economic development, land tenure, and agricultural finance in Nigeria.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['production'],
        examWeight: 0.07,
        examTypes: ['waec', 'neco'],
      },
    ],
  },
  {
    slug: 'government',
    name: 'Government',
    hue: '#8E3F5A',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Political science covering concepts, constitutional development, arms of government, and international relations.',
    topics: [
      {
        slug: 'political-concepts',
        name: 'Political Concepts',
        order: 1,
        description: 'State, nation, sovereignty, legitimacy, power, authority, and political culture.',
        estimatedMinutes: 50,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'constitutional-development',
        name: 'Constitutional Development in Nigeria',
        order: 2,
        description: 'Richards, Macpherson, Lyttleton Constitutions, independence, and post-independence constitutional changes.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['political-concepts'],
        examWeight: 0.12,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'arms-of-government',
        name: 'Arms of Government',
        order: 3,
        description: 'Legislature, executive, and judiciary — structure, functions, and relationship in Nigeria.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['political-concepts'],
        examWeight: 0.11,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'political-parties',
        name: 'Political Parties',
        order: 4,
        description: 'Functions of political parties, party systems, pressure groups, and interest groups in Nigeria.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['constitutional-development'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'federalism',
        name: 'Federalism',
        order: 5,
        description: 'Features, merits, and demerits of federalism; revenue allocation and intergovernmental relations in Nigeria.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['arms-of-government'],
        examWeight: 0.11,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'electoral-systems',
        name: 'Electoral Systems',
        order: 6,
        description: 'Types of electoral systems, INEC, electoral process, and problems of elections in Nigeria.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['political-parties'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'international-relations',
        name: 'International Relations',
        order: 7,
        description: "Nigeria's foreign policy, international organisations (UN, AU, ECOWAS), and diplomacy.",
        estimatedMinutes: 55,
        prerequisiteSlugs: [],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'human-rights',
        name: 'Human Rights',
        order: 8,
        description: 'Fundamental rights in the Nigerian Constitution, limitations, and enforcement mechanisms.',
        estimatedMinutes: 45,
        prerequisiteSlugs: ['constitutional-development'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'local-government',
        name: 'Local Government',
        order: 9,
        description: 'History, structure, functions, and problems of local government in Nigeria.',
        estimatedMinutes: 45,
        prerequisiteSlugs: ['federalism'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'public-administration',
        name: 'Public Administration',
        order: 10,
        description: 'Civil service, bureaucracy, public corporations, and administrative reform in Nigeria.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['arms-of-government'],
        examWeight: 0.10,
        examTypes: ['waec', 'neco'],
      },
    ],
  },
  {
    slug: 'literature',
    name: 'Literature in English',
    hue: '#5A3F8E',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Critical reading and analysis of poetry, prose, and drama with focus on African and Nigerian texts.',
    topics: [
      {
        slug: 'poetry-analysis',
        name: 'Poetry Analysis',
        order: 1,
        description: 'Reading and interpreting poems: structure, voice, tone, imagery, and thematic concerns.',
        estimatedMinutes: 65,
        prerequisiteSlugs: [],
        examWeight: 0.12,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'prose-fiction',
        name: 'Prose Fiction',
        order: 2,
        description: 'Novel analysis: plot, character, setting, point of view, theme, and style in prescribed texts.',
        estimatedMinutes: 70,
        prerequisiteSlugs: [],
        examWeight: 0.13,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'drama',
        name: 'Drama',
        order: 3,
        description: 'Analysis of prescribed plays: dramatic structure, conflict, stage conventions, and interpretation.',
        estimatedMinutes: 70,
        prerequisiteSlugs: [],
        examWeight: 0.13,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'literary-devices',
        name: 'Literary and Poetic Devices',
        order: 4,
        description: 'Identification and effect of alliteration, assonance, enjambment, paradox, and other devices.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['poetry-analysis'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'african-literature',
        name: 'African Literature',
        order: 5,
        description: 'Themes, writers, and cultural contexts of canonical African literary works.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['prose-fiction'],
        examWeight: 0.12,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'nigerian-literature',
        name: 'Nigerian Literature',
        order: 6,
        description: 'History of Nigerian writing in English; major authors and their works from Achebe to contemporary voices.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['african-literature'],
        examWeight: 0.12,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'oral-literature',
        name: 'Oral Literature and Folklore',
        order: 7,
        description: 'Oral traditions: proverbs, folktales, myths, and their relationship to written literature.',
        estimatedMinutes: 50,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['waec', 'neco'],
      },
      {
        slug: 'literary-criticism',
        name: 'Literary Criticism and Theory',
        order: 8,
        description: 'Basic critical approaches for evaluating and discussing literature analytically.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['prose-fiction', 'drama'],
        examWeight: 0.09,
        examTypes: ['waec', 'neco'],
      },
      {
        slug: 'unseen-texts',
        name: 'Unseen Texts',
        order: 9,
        description: 'Applying literary skills to previously unseen poems and prose passages under exam conditions.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['poetry-analysis', 'prose-fiction'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
    ],
  },
  {
    slug: 'geography',
    name: 'Geography',
    hue: '#2F6B3F',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Physical and human geography covering map work, landforms, climate, population, and regional studies.',
    topics: [
      {
        slug: 'mapping-and-map-reading',
        name: 'Mapping and Map Reading',
        order: 1,
        description: 'Topographic maps, scale, grid references, cross-sections, and interpretation of map features.',
        estimatedMinutes: 65,
        prerequisiteSlugs: [],
        examWeight: 0.11,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'weather-and-climate',
        name: 'Weather and Climate',
        order: 2,
        description: 'Elements of weather, climate classification, climate change, and climatic regions of Nigeria.',
        estimatedMinutes: 65,
        prerequisiteSlugs: [],
        examWeight: 0.11,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'rock-types',
        name: 'Rock Types and Weathering',
        order: 3,
        description: 'Igneous, sedimentary, and metamorphic rocks; physical, chemical, and biological weathering processes.',
        estimatedMinutes: 55,
        prerequisiteSlugs: [],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'plate-tectonics',
        name: 'Plate Tectonics and Landforms',
        order: 4,
        description: 'Plate boundaries, earthquakes, volcanoes, folding, faulting, and associated landforms.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['rock-types'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'drainage-systems',
        name: 'Drainage Systems',
        order: 5,
        description: 'River processes, drainage patterns, river capture, lakes, and coastal landforms.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['rock-types'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'agriculture-geography',
        name: 'Agriculture',
        order: 6,
        description: 'Types of farming, factors affecting agriculture, land use patterns, and agricultural regions.',
        estimatedMinutes: 55,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'population-geography',
        name: 'Population Geography',
        order: 7,
        description: 'Population distribution, density, growth, migration, and urbanisation in Nigeria and Africa.',
        estimatedMinutes: 55,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'economic-geography',
        name: 'Economic Geography',
        order: 8,
        description: 'Natural resources, industrialisation, trade, and transport systems in West Africa.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['agriculture-geography'],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'west-africa',
        name: 'Regional Geography — West Africa',
        order: 9,
        description: 'Physical features, climate, resources, and economic activities of major West African countries.',
        estimatedMinutes: 65,
        prerequisiteSlugs: ['weather-and-climate', 'population-geography'],
        examWeight: 0.11,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'environmental-geography',
        name: 'Environmental Geography',
        order: 10,
        description: 'Environmental degradation, desertification, deforestation, and conservation strategies.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['weather-and-climate'],
        examWeight: 0.08,
        examTypes: ['waec', 'neco'],
      },
      {
        slug: 'settlement-geography',
        name: 'Settlement Geography',
        order: 11,
        description: 'Types and patterns of settlement, urban growth, urban problems, and rural-urban migration.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['population-geography'],
        examWeight: 0.06,
        examTypes: ['waec', 'neco'],
      },
    ],
  },
  {
    slug: 'commerce',
    name: 'Commerce',
    hue: '#7C766B',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Business and commercial activities covering trade, business organisations, banking, insurance, and marketing.',
    topics: [
      {
        slug: 'trade-concepts',
        name: 'Trade Concepts',
        order: 1,
        description: 'Definition and importance of trade, home and foreign trade, channels of distribution.',
        estimatedMinutes: 45,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'types-of-trade',
        name: 'Types of Trade',
        order: 2,
        description: 'Wholesale and retail trade, functions of wholesalers and retailers, and trends in distribution.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['trade-concepts'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'business-organisations',
        name: 'Business Organisations',
        order: 3,
        description: 'Sole proprietorships, partnerships, limited liability companies, cooperatives, and public enterprises.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.12,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'transportation',
        name: 'Transportation',
        order: 4,
        description: 'Modes of transport, documents used in transportation, and factors influencing choice of transport.',
        estimatedMinutes: 50,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'banking-services',
        name: 'Banking Services',
        order: 5,
        description: 'Commercial bank functions, banking instruments, e-banking, and the role of the Central Bank.',
        estimatedMinutes: 60,
        prerequisiteSlugs: [],
        examWeight: 0.11,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'insurance',
        name: 'Insurance',
        order: 6,
        description: 'Principles of insurance, types of insurance, insurance documents, and the insurance market.',
        estimatedMinutes: 55,
        prerequisiteSlugs: [],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'warehousing',
        name: 'Warehousing',
        order: 7,
        description: 'Functions of warehouses, types of warehouses, bonded warehouses, and their role in trade.',
        estimatedMinutes: 40,
        prerequisiteSlugs: ['trade-concepts'],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'advertising',
        name: 'Advertising and Sales Promotion',
        order: 8,
        description: 'Functions of advertising, media of advertising, sales promotion techniques, and consumer protection.',
        estimatedMinutes: 45,
        prerequisiteSlugs: ['trade-concepts'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'international-trade-commerce',
        name: 'International Trade',
        order: 9,
        description: 'Documents in foreign trade, terms of trade (FOB, CIF), trade organisations, and balance of trade.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['types-of-trade'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'communication-in-business',
        name: 'Communication in Business',
        order: 10,
        description: 'Channels of business communication, telecommunications, and IT in modern commerce.',
        estimatedMinutes: 40,
        prerequisiteSlugs: [],
        examWeight: 0.07,
        examTypes: ['waec', 'neco'],
      },
      {
        slug: 'home-trade-documents',
        name: 'Home Trade Documents',
        order: 11,
        description: 'Trade documents used in domestic trade: enquiry, quotation, order, invoice, and statement of account.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['types-of-trade'],
        examWeight: 0.07,
        examTypes: ['jamb', 'waec', 'neco'],
      },
    ],
  },
  {
    slug: 'agricultural-science',
    name: 'Agricultural Science',
    hue: '#8E5A2B',
    examTypes: ['jamb', 'waec', 'neco'],
    description: 'Principles of agriculture including soil science, crop production, animal husbandry, and agribusiness.',
    topics: [
      {
        slug: 'soil-science',
        name: 'Soil Science',
        order: 1,
        description: 'Soil formation, composition, types, properties, fertility, and conservation practices.',
        estimatedMinutes: 65,
        prerequisiteSlugs: [],
        examWeight: 0.11,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'crop-production',
        name: 'Crop Production',
        order: 2,
        description: 'Land preparation, planting methods, cultural practices, and harvest of major Nigerian crops.',
        estimatedMinutes: 70,
        prerequisiteSlugs: ['soil-science'],
        examWeight: 0.13,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'animal-husbandry',
        name: 'Animal Husbandry',
        order: 3,
        description: 'Livestock breeds, nutrition, housing, health management, and production systems.',
        estimatedMinutes: 65,
        prerequisiteSlugs: [],
        examWeight: 0.12,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'farm-machinery',
        name: 'Farm Machinery and Mechanisation',
        order: 4,
        description: 'Types of farm tools and machinery, their uses, maintenance, and the role of mechanisation in Nigeria.',
        estimatedMinutes: 50,
        prerequisiteSlugs: ['crop-production'],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'pest-disease-control',
        name: 'Pest and Disease Control',
        order: 5,
        description: 'Identification, effects, and control of crop pests, diseases, weeds, and animal parasites.',
        estimatedMinutes: 60,
        prerequisiteSlugs: ['crop-production', 'animal-husbandry'],
        examWeight: 0.11,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'agricultural-economics',
        name: 'Agricultural Economics and Extension',
        order: 6,
        description: 'Costs of production, farm records, marketing of agricultural produce, and agricultural extension services.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['crop-production'],
        examWeight: 0.10,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'fisheries',
        name: 'Fisheries',
        order: 7,
        description: 'Importance of fish farming, types of fisheries, fish pond management, and fish processing.',
        estimatedMinutes: 50,
        prerequisiteSlugs: [],
        examWeight: 0.09,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'forestry',
        name: 'Forestry',
        order: 8,
        description: 'Types of forests, economic importance, forest conservation, and afforestation programmes in Nigeria.',
        estimatedMinutes: 50,
        prerequisiteSlugs: [],
        examWeight: 0.08,
        examTypes: ['jamb', 'waec', 'neco'],
      },
      {
        slug: 'plant-and-animal-genetics',
        name: 'Agricultural Genetics and Breeding',
        order: 9,
        description: 'Basic genetics applied to plant and animal breeding; hybrid vigour and selection methods.',
        estimatedMinutes: 55,
        prerequisiteSlugs: ['crop-production', 'animal-husbandry'],
        examWeight: 0.09,
        examTypes: ['waec', 'neco'],
      },
      {
        slug: 'irrigation-drainage',
        name: 'Irrigation and Water Management',
        order: 10,
        description: 'Importance of irrigation, types of irrigation systems, drainage methods, and water conservation.',
        estimatedMinutes: 45,
        prerequisiteSlugs: ['soil-science'],
        examWeight: 0.09,
        examTypes: ['waec', 'neco'],
      },
    ],
  },
]
